# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bgrassian/cam-proc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bgrassian/cam-proc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/bgrassian/cam-proc && $(CMAKE_COMMAND) -E cmake_progress_start /home/bgrassian/cam-proc/CMakeFiles /home/bgrassian/cam-proc/src/ROIProc/CMakeFiles/progress.marks
	cd /home/bgrassian/cam-proc && $(MAKE) -f CMakeFiles/Makefile2 src/ROIProc/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bgrassian/cam-proc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/bgrassian/cam-proc && $(MAKE) -f CMakeFiles/Makefile2 src/ROIProc/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/bgrassian/cam-proc && $(MAKE) -f CMakeFiles/Makefile2 src/ROIProc/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/bgrassian/cam-proc && $(MAKE) -f CMakeFiles/Makefile2 src/ROIProc/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/bgrassian/cam-proc && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/ROIProc/CMakeFiles/ROIProc.dir/rule:
	cd /home/bgrassian/cam-proc && $(MAKE) -f CMakeFiles/Makefile2 src/ROIProc/CMakeFiles/ROIProc.dir/rule
.PHONY : src/ROIProc/CMakeFiles/ROIProc.dir/rule

# Convenience name for target.
ROIProc: src/ROIProc/CMakeFiles/ROIProc.dir/rule

.PHONY : ROIProc

# fast build rule for target.
ROIProc/fast:
	cd /home/bgrassian/cam-proc && $(MAKE) -f src/ROIProc/CMakeFiles/ROIProc.dir/build.make src/ROIProc/CMakeFiles/ROIProc.dir/build
.PHONY : ROIProc/fast

blobdetection.o: blobdetection.cpp.o

.PHONY : blobdetection.o

# target to build an object file
blobdetection.cpp.o:
	cd /home/bgrassian/cam-proc && $(MAKE) -f src/ROIProc/CMakeFiles/ROIProc.dir/build.make src/ROIProc/CMakeFiles/ROIProc.dir/blobdetection.cpp.o
.PHONY : blobdetection.cpp.o

blobdetection.i: blobdetection.cpp.i

.PHONY : blobdetection.i

# target to preprocess a source file
blobdetection.cpp.i:
	cd /home/bgrassian/cam-proc && $(MAKE) -f src/ROIProc/CMakeFiles/ROIProc.dir/build.make src/ROIProc/CMakeFiles/ROIProc.dir/blobdetection.cpp.i
.PHONY : blobdetection.cpp.i

blobdetection.s: blobdetection.cpp.s

.PHONY : blobdetection.s

# target to generate assembly for a file
blobdetection.cpp.s:
	cd /home/bgrassian/cam-proc && $(MAKE) -f src/ROIProc/CMakeFiles/ROIProc.dir/build.make src/ROIProc/CMakeFiles/ROIProc.dir/blobdetection.cpp.s
.PHONY : blobdetection.cpp.s

bloblibproc.o: bloblibproc.cpp.o

.PHONY : bloblibproc.o

# target to build an object file
bloblibproc.cpp.o:
	cd /home/bgrassian/cam-proc && $(MAKE) -f src/ROIProc/CMakeFiles/ROIProc.dir/build.make src/ROIProc/CMakeFiles/ROIProc.dir/bloblibproc.cpp.o
.PHONY : bloblibproc.cpp.o

bloblibproc.i: bloblibproc.cpp.i

.PHONY : bloblibproc.i

# target to preprocess a source file
bloblibproc.cpp.i:
	cd /home/bgrassian/cam-proc && $(MAKE) -f src/ROIProc/CMakeFiles/ROIProc.dir/build.make src/ROIProc/CMakeFiles/ROIProc.dir/bloblibproc.cpp.i
.PHONY : bloblibproc.cpp.i

bloblibproc.s: bloblibproc.cpp.s

.PHONY : bloblibproc.s

# target to generate assembly for a file
bloblibproc.cpp.s:
	cd /home/bgrassian/cam-proc && $(MAKE) -f src/ROIProc/CMakeFiles/ROIProc.dir/build.make src/ROIProc/CMakeFiles/ROIProc.dir/bloblibproc.cpp.s
.PHONY : bloblibproc.cpp.s

contourassembler.o: contourassembler.cpp.o

.PHONY : contourassembler.o

# target to build an object file
contourassembler.cpp.o:
	cd /home/bgrassian/cam-proc && $(MAKE) -f src/ROIProc/CMakeFiles/ROIProc.dir/build.make src/ROIProc/CMakeFiles/ROIProc.dir/contourassembler.cpp.o
.PHONY : contourassembler.cpp.o

contourassembler.i: contourassembler.cpp.i

.PHONY : contourassembler.i

# target to preprocess a source file
contourassembler.cpp.i:
	cd /home/bgrassian/cam-proc && $(MAKE) -f src/ROIProc/CMakeFiles/ROIProc.dir/build.make src/ROIProc/CMakeFiles/ROIProc.dir/contourassembler.cpp.i
.PHONY : contourassembler.cpp.i

contourassembler.s: contourassembler.cpp.s

.PHONY : contourassembler.s

# target to generate assembly for a file
contourassembler.cpp.s:
	cd /home/bgrassian/cam-proc && $(MAKE) -f src/ROIProc/CMakeFiles/ROIProc.dir/build.make src/ROIProc/CMakeFiles/ROIProc.dir/contourassembler.cpp.s
.PHONY : contourassembler.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	cd /home/bgrassian/cam-proc && $(MAKE) -f src/ROIProc/CMakeFiles/ROIProc.dir/build.make src/ROIProc/CMakeFiles/ROIProc.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	cd /home/bgrassian/cam-proc && $(MAKE) -f src/ROIProc/CMakeFiles/ROIProc.dir/build.make src/ROIProc/CMakeFiles/ROIProc.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	cd /home/bgrassian/cam-proc && $(MAKE) -f src/ROIProc/CMakeFiles/ROIProc.dir/build.make src/ROIProc/CMakeFiles/ROIProc.dir/main.cpp.s
.PHONY : main.cpp.s

morphops.o: morphops.cpp.o

.PHONY : morphops.o

# target to build an object file
morphops.cpp.o:
	cd /home/bgrassian/cam-proc && $(MAKE) -f src/ROIProc/CMakeFiles/ROIProc.dir/build.make src/ROIProc/CMakeFiles/ROIProc.dir/morphops.cpp.o
.PHONY : morphops.cpp.o

morphops.i: morphops.cpp.i

.PHONY : morphops.i

# target to preprocess a source file
morphops.cpp.i:
	cd /home/bgrassian/cam-proc && $(MAKE) -f src/ROIProc/CMakeFiles/ROIProc.dir/build.make src/ROIProc/CMakeFiles/ROIProc.dir/morphops.cpp.i
.PHONY : morphops.cpp.i

morphops.s: morphops.cpp.s

.PHONY : morphops.s

# target to generate assembly for a file
morphops.cpp.s:
	cd /home/bgrassian/cam-proc && $(MAKE) -f src/ROIProc/CMakeFiles/ROIProc.dir/build.make src/ROIProc/CMakeFiles/ROIProc.dir/morphops.cpp.s
.PHONY : morphops.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ROIProc"
	@echo "... blobdetection.o"
	@echo "... blobdetection.i"
	@echo "... blobdetection.s"
	@echo "... bloblibproc.o"
	@echo "... bloblibproc.i"
	@echo "... bloblibproc.s"
	@echo "... contourassembler.o"
	@echo "... contourassembler.i"
	@echo "... contourassembler.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... morphops.o"
	@echo "... morphops.i"
	@echo "... morphops.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/bgrassian/cam-proc && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

